[[items]]
name = "ab_glyph"
source = "crates"
categories = ["textrendering"]

[[items]]
name = "alto"
source = "crates"
categories = ["audio"]

[[items]]
name = "ambisonic"
source = "crates"
categories = ["audio"]

[[items]]
name = "amethyst"
source = "crates"
categories = ["engines"]

[[items]]
name = "amethyst/naia"
source = "github"
categories = ["networking"]

[[items]]
name = "amethyst_network"
source = "crates"
categories = ["networking"]

[[items]]
name = "aseprite"
source = "crates"
categories = ["tools"]

[[items]]
name = "ash"
source = "crates"
categories = ["3drendering"]
gitter_url = "https://gitter.im/MaikKlein/ash"

[[items]]
name = "assets_manager"
source = "crates"
categories = ["tools"]

[[items]]
name = "audir"
source = "crates"
categories = ["audio"]

[[items]]
name = "basis-universal"
source = "crates"
categories = ["tools"]

[[items]]
name = "beehive"
source = "crates"
categories = ["tools"]

[[items]]
name = "beryllium"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "bevy"
source = "crates"
categories = ["engines"]

[[items]]
name = "bevy_ecs"
source = "crates"
categories = ["ecs"]

[[items]]
name = "bgfx-rs"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "big-brain"
source = "crates"
categories = ["ai"]

[[items]]
name = "blend"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "blit"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "bmfont"
source = "crates"
categories = ["textrendering"]

[[items]]
name = "building-blocks"
source = "crates"
categories = ["tools", "mesh"]

[[items]]
name = "bvh"
source = "crates"
categories = ["math"]

[[items]]
name = "calx-ecs"
source = "crates"
categories = ["ecs"]

[[items]]
name = "caper"
source = "crates"
categories = ["engines"]

[[items]]
name = "cgmath"
source = "crates"
categories = ["math"]

[[items]]
name = "ChariotEngine/Chariot"
source = "github"
categories = ["engines"]

[[items]]
name = "chess-engine"
source = "crates"
categories = ["ai"]

[[items]]
name = "claxon"
source = "crates"
categories = ["audio"]

[[items]]
name = "coffee"
source = "crates"
categories = ["engines"]

[[items]]
name = "collada"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "collider"
source = "crates"
categories = ["physics"]

[[items]]
name = "conrod_core"
source = "crates"
categories = ["ui"]

[[items]]
name = "console_engine"
source = "crates"
categories = ["engines", "tools"]

[[items]]
name = "const-tweaker"
source = "crates"
categories = ["tools"]

[[items]]
name = "corange-rs"
source = "crates"
categories = ["engines"]

[[items]]
name = "cpal"
source = "crates"
categories = ["audio"]

[[items]]
name = "crayon"
source = "crates"
categories = ["engines"]

[[items]]
name = "crevice"
source = "crates"
categories = ["shader"]

[[items]]
name = "crow"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "crystalorb"
source = "crates"
categories = ["networking"]

[[items]]
name = "datachannel"
source = "crates"
categories = ["networking"]

[[items]]
name = "dces"
source = "crates"
categories = ["ecs"]

[[items]]
name = "density-mesh-core"
source = "crates"
categories = ["tools", "mesh"]

[[items]]
name = "density-mesh-image"
source = "crates"
categories = ["tools", "mesh"]

[[items]]
name = "distill"
source = "crates"
categories = ["tools"]

[[items]]
name = "doryen-rs"
source = "crates"
categories = ["engines"]

[[items]]
name = "dot_vox"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "dotrix"
source = "crates"
categories = ["3drendering", "engines", "ecs"]

[[items]]
name = "dual_quaternion"
source = "crates"
categories = ["math"]

[[items]]
name = "duysqubix/MuOxi"
source = "github"
categories = ["engines"]

[[items]]
name = "dyon"
source = "crates"
categories = ["scripting"]

[[items]]
name = "ears"
source = "crates"
categories = ["audio"]

[[items]]
name = "egui"
source = "crates"
categories = ["ui"]

[[items]]
name = "Ellie Language"
description = "A type-safe scripting language"
categories = ["scripting"]
image = "/assets/img/ellie_language.png"
repository_url = "https://github.com/behemehal/Ellie-Language"
homepage_url = "https://ellie.behemehal.net"
gitter_url = "https://gitter.im/ellie-lang/community"

[[items]]
name = "EmbarkStudios/rust-gpu"
source = "github"
categories = ["shader"]

[[items]]
name = "enet"
source = "crates"
categories = ["networking"]

[[items]]
name = "euc"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "euclid"
source = "crates"
categories = ["math"]

[[items]]
name = "euler"
source = "crates"
categories = ["math"]
gitter_url = "https://gitter.im/euler-rs/Lobby"

[[items]]
name = "ezing"
source = "crates"
categories = ["tools"]

[[items]]
name = "fbxcel-dom"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "femtovg"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "fermium"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "fmod"
source = "crates"
categories = ["audio"]

[[items]]
name = "fontdue"
source = "crates"
categories = ["textrendering"]

[[items]]
name = "froggy"
source = "crates"
categories = ["ecs"]

[[items]]
name = "fungui"
source = "crates"
categories = ["ui"]

[[items]]
name = "gate"
source = "crates"
categories = ["engines"]

[[items]]
name = "gdnative"
source = "crates"
categories = ["engines"]

[[items]]
name = "generic-matrix"
source = "crates"
categories = ["math"]

[[items]]
name = "gfx"
source = "crates"
categories = ["3drendering"]
gitter_url = "https://gitter.im/gfx-rs/gfx"

[[items]]
name = "gfx-hal"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "ggez"
source = "crates"
categories = ["engines"]

[[items]]
name = "Gigoteur/UnicornConsole"
source = "github"
categories = ["engines"]
gitter_url = "https://gitter.im/UnicornConsole/Lobby"

[[items]]
name = "gilrs"
source = "crates"
categories = ["input"]

[[items]]
name = "gl"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "glam"
source = "crates"
categories = ["math"]

[[items]]
name = "glfw"
source = "crates"
categories = ["3drendering", "windowing"]

[[items]]
name = "glium"
source = "crates"
categories = ["3drendering"]
gitter_url = "https://gitter.im/tomaka/glium"

[[items]]
name = "glow"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "glsp"
source = "crates"
categories = ["scripting"]

[[items]]
name = "gltf"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "gluon"
source = "crates"
categories = ["scripting"]
gitter_url = "https://gitter.im/gluon-lang/gluon"

[[items]]
name = "glutin"
source = "crates"
categories = ["3drendering", "windowing"]
gitter_url = "https://gitter.im/tomaka/glutin"

[[items]]
name = "gme"
source = "crates"
categories = ["audio"]

[[items]]
name = "graco"
source = "crates"
homepage_url = "https://gitlab.com/chrisrabotin/graco"
categories = ["ai"]

[[items]]
name = "grr"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "hecs"
source = "crates"
categories = ["ecs"]

[[items]]
name = "hex2d"
source = "crates"
categories = ["tools"]

[[items]]
name = "hexasphere"
source = "crates"
categories = ["tools", "mesh"]

[[items]]
name = "hlua"
source = "crates"
categories = ["scripting"]

[[items]]
name = "Hossein-Noroozpour/vulkust"
source = "github"
categories = ["engines"]

[[items]]
name = "hound"
source = "crates"
categories = ["audio"]

[[items]]
name = "huxingyi/dust3d"
source = "github"
categories = ["tools"]
gitter_url = "https://dust3d.discourse.group/"
homepage_url = "https://dust3d.org/"

[[items]]
name = "I3ck/rust-3d"
source = "github"
categories = ["math"]

[[items]]
name = "iced"
source = "crates"
categories = ["ui"]
gitter_url = "https://iced.zulipchat.com"

[[items]]
name = "image"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "imgui"
source = "crates"
categories = ["ui"]

[[items]]
name = "imgui-ext"
source = "crates"
categories = ["ui"]

[[items]]
name = "imgui-inspect"
source = "crates"
categories = ["ui"]

[[items]]
name = "immi"
source = "crates"
categories = ["ui"]

[[items]]
name = "include-merkle"
source = "crates"
categories = ["shader"]

[[items]]
name = "inline-spirv"
source = "crates"
categories = ["shader"]

[[items]]
name = "keeshond"
source = "crates"
categories = ["engines"]

[[items]]
name = "keeshond_datapack"
source = "crates"
categories = ["tools"]

[[items]]
name = "ketos"
source = "crates"
categories = ["scripting"]

[[items]]
name = "keyframe"
source = "crates"
categories = ["tools"]

[[items]]
name = "kira"
source = "crates"
categories = ["audio"]

[[items]]
name = "kiss3d"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "laminar"
source = "crates"
categories = ["networking"]

[[items]]
name = "legion"
source = "crates"
categories = ["ecs"]

[[items]]
name = "lewton"
source = "crates"
categories = ["audio"]

[[items]]
name = "libovr"
source = "crates"
categories = ["vr"]

[[items]]
name = "lichen"
source = "crates"
categories = ["scripting"]

[[items]]
name = "liquidfun"
source = "crates"
categories = ["physics"]

[[items]]
name = "luajit"
source = "crates"
categories = ["scripting"]

[[items]]
name = "luminance"
source = "crates"
categories = ["3drendering"]
gitter_url = "https://gitter.im/phaazon/luminance-rs"

[[items]]
name = "lyon"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "macroquad"
source = "crates"
categories = ["engines"]
homepage_url = "https://github.com/not-fl3/miniquad"

[[items]]
name = "meshopt"
source = "crates"
categories = ["mesh"]

[[items]]
name = "message-io"
source = "crates"
categories = ["networking"]
homepage_url = "https://github.com/lemunozm/message-io"

[[items]]
name = "mgf"
source = "crates"
categories = ["physics"]

[[items]]
name = "minifb"
source = "crates"
categories = ["windowing"]

[[items]]
name = "minimp3"
source = "crates"
categories = ["audio"]

[[items]]
name = "miniquad"
source = "crates"
categories = ["2drendering", "3drendering"]
homepage_url = "https://github.com/not-fl3/miniquad"

[[items]]
name = "mint"
source = "crates"
categories = ["math"]

[[items]]
name = "mlua"
source = "crates"
categories = ["scripting"]

[[items]]
name = "mod_player"
source = "crates"
categories = ["audio"]

[[items]]
name = "modio"
source = "crates"
categories = ["tools"]
gitter_url = "https://discord.mod.io/"

[[items]]
name = "modulator"
source = "crates"
categories = ["tools"]

[[items]]
name = "mold2d"
source = "crates"
categories = ["engines"]

[[items]]
name = "mun-lang/mun"
source = "github"
categories = ["scripting"]
homepage_url = "https://mun-lang.org"

[[items]]
name = "naga"
source = "crates"
categories = ["shader"]
homepage_url = "https://github.com/gfx-rs/naga"

[[items]]
name = "nalgebra"
source = "crates"
categories = ["math"]

[[items]]
name = "navmesh"
source = "crates"
categories = ["ai"]
homepage_url = "https://github.com/PsichiX/navmesh"

[[items]]
name = "ncollide2d"
source = "crates"
categories = ["physics"]
homepage_url = "https://ncollide.org"

[[items]]
name = "ncollide3d"
source = "crates"
categories = ["physics"]
homepage_url = "https://ncollide.org"

[[items]]
name = "noise"
source = "crates"
categories = ["tools"]

[[items]]
name = "nphysics2d"
source = "crates"
categories = ["physics"]
homepage_url = "https://nphysics.org"

[[items]]
name = "nphysics3d"
source = "crates"
categories = ["physics"]
homepage_url = "https://nphysics.org"

[[items]]
name = "nuklear-rust"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "nuklear-rust"
source = "crates"
categories = ["ui"]

[[items]]
name = "obj"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "obj-rs"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "oddio"
source = "crates"
categories = ["audio"]

[[items]]
name = "ogmo3"
source = "crates"
categories = ["tools"]

[[items]]
name = "olson-sean-k/plexus"
source = "github"
categories = ["mesh"]
homepage_url = "https://plexus.rs"

[[items]]
name = "opensubdiv-petite"
source = "crates"
categories = ["mesh", "3drendering"]

[[items]]
name = "openvr"
source = "crates"
categories = ["vr"]
gitter_url = "https://gitter.im/rust-openvr/rust-openvr"

[[items]]
name = "openxr"
source = "crates"
categories = ["vr"]

[[items]]
name = "optimath"
source = "crates"
categories = ["math"]

[[items]]
name = "oxygen_quark"
source = "crates"
categories = ["math"]

[[items]]
name = "oxygengine"
source = "crates"
categories = ["engines"]
homepage_url = "https://github.com/PsichiX/Oxygengine"

[[items]]
name = "palette"
source = "crates"
categories = ["math"]

[[items]]
name = "pareen"
source = "crates"
categories = ["animation"]

[[items]]
name = "passerine"
source = "crates"
categories = ["scripting"]

[[items]]
name = "pathfinding"
source = "crates"
categories = ["ai"]

[[items]]
name = "peacock"
source = "crates"
categories = ["engines"]

[[items]]
name = "physme"
source = "crates"
categories = ["physics"]

[[items]]
name = "physx"
source = "crates"
categories = ["physics"]
homepage_url = "https://github.com/EmbarkStudios/physx-rs"

[[items]]
name = "piston"
source = "crates"
categories = ["engines"]

[[items]]
name = "piston-ai_behavior"
source = "crates"
categories = ["ai"]

[[items]]
name = "piston2d-graphics"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "piston_window"
source = "crates"
categories = ["windowing"]

[[items]]
name = "pixels"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "polyhedron-ops"
source = "crates"
categories = ["mesh"]

[[items]]
name = "polystrip"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "portmidi"
source = "crates"
categories = ["audio"]

[[items]]
name = "profiling"
source = "crates"
categories = ["tools"]

[[items]]
name = "pyro"
source = "crates"
categories = ["ecs"]

[[items]]
name = "pyxel"
source = "crates"
categories = ["tools"]

[[items]]
name = "quaternion"
source = "crates"
categories = ["math"]

[[items]]
name = "quicksilver"
source = "crates"
categories = ["engines"]

[[items]]
name = "quilkin"
source = "crates"
categories = ["networking"]

[[items]]
name = "quinn"
source = "crates"
categories = ["networking"]

[[items]]
name = "rafx"
source = "crates"
categories = ["2drendering", "3drendering"]

[[items]]
name = "rapier2d"
source = "crates"
categories = ["physics"]

[[items]]
name = "rapier3d"
source = "crates"
categories = ["physics"]

[[items]]
name = "raylib"
source = "crates"
categories = ["engines"]

[[items]]
name = "rectangle-pack"
source = "crates"
categories = ["tools"]

[[items]]
name = "rendology"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "rendy"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "rg3d"
source = "crates"
categories = ["engines"]

[[items]]
name = "rg3d-sound"
source = "crates"
categories = ["audio"]

[[items]]
name = "rhai"
source = "crates"
categories = ["scripting"]

[[items]]
name = "rhusics"
source = "crates"
categories = ["physics"]

[[items]]
name = "rltk"
source = "crates"
categories = ["engines"]

[[items]]
name = "rlua"
source = "crates"
categories = ["scripting"]

[[items]]
name = "rodio"
source = "crates"
categories = ["audio"]

[[items]]
name = "rotsprite"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "rovr"
source = "crates"
categories = ["vr"]

[[items]]
name = "rsaarelm/vitral"
source = "github"
categories = ["ui"]

[[items]]
name = "rsoundio"
source = "crates"
categories = ["audio"]

[[items]]
name = "rune"
source = "crates"
categories = ["scripting"]

[[items]]
name = "rust-webvr"
source = "crates"
categories = ["vr"]

[[items]]
name = "rustpython"
source = "crates"
categories = ["scripting"]

[[items]]
name = "rusttype"
source = "crates"
categories = ["textrendering"]

[[items]]
name = "rusty_engine"
source = "crates"
categories = ["engines"]

[[items]]
name = "salva2d"
source = "crates"
categories = ["physics"]
homepage_url = "https://salva.rs"

[[items]]
name = "salva3d"
source = "crates"
categories = ["physics"]
homepage_url = "https://salva.rs"

[[items]]
name = "sciter-rs"
source = "crates"
categories = ["ui"]

[[items]]
name = "screen-13"
source = "crates"
categories = ["3drendering", "engines"]

[[items]]
name = "sdl2"
source = "crates"
categories = ["2drendering", "audio", "engines", "input", "windowing"]

[[items]]
name = "sfml"
source = "crates"
categories = ["2drendering", "engines"]
homepage_url = "https://github.com/jeremyletang/rust-sfml"

[[items]]
name = "sfxr"
source = "crates"
categories = ["audio"]

[[items]]
name = "shaderc"
source = "crates"
categories = ["shader"]

[[items]]
name = "sharecart1000"
source = "crates"
categories = ["tools"]

[[items]]
name = "shipyard"
source = "crates"
categories = ["ecs"]
gitter_url = "https://gitter.im/leudz-shipyard/community"

[[items]]
name = "Siebencorgie/jakar-engine"
source = "github"
categories = ["engines"]
homepage_url = "https://gitlab.com/Siebencorgie/jakar-engine"

[[items]]
name = "skulpin"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "soloud"
source = "crates"
categories = ["audio"]

[[items]]
name = "specs"
source = "crates"
categories = ["ecs"]
gitter_url = "https://gitter.im/slide-rs/specs"

[[items]]
name = "spirq"
source = "crates"
categories = ["shader"]

[[items]]
name = "spirv-reflect"
source = "crates"
categories = ["shader"]

[[items]]
name = "splines"
source = "crates"
categories = ["math"]

[[items]]
name = "sprite"
source = "crates"
categories = ["tools"]

[[items]]
name = "steering"
source = "crates"
categories = ["ai"]

[[items]]
name = "superluminal-perf"
source = "crates"
categories = ["tools"]

[[items]]
name = "tcod"
source = "crates"
categories = ["tools"]

[[items]]
name = "tessellation"
source = "crates"
categories = ["mesh"]

[[items]]
name = "tetra"
source = "crates"
categories = ["engines"]

[[items]]
name = "texture-synthesis"
source = "crates"
categories = ["tools"]

[[items]]
name = "three"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "throne"
source = "crates"
categories = ["scripting"]

[[items]]
name = "tiled"
source = "crates"
categories = ["tools"]

[[items]]
name = "tiny-skia"
source = "crates"
categories = ["2drendering"]

[[items]]
name = "tobj"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "torchbear"
source = "crates"
categories = ["scripting"]

[[items]]
name = "turbine"
source = "crates"
categories = ["engines"]

[[items]]
name = "tuzz/game-loop"
source = "github"
categories = ["tools"]

[[items]]
name = "ultraviolet"
source = "crates"
categories = ["math"]

[[items]]
name = "uniform-cubic-splines"
source = "crates"
categories = ["math"]

[[items]]
name = "usfx"
source = "crates"
categories = ["audio"]

[[items]]
name = "vecmath"
source = "crates"
categories = ["math"]

[[items]]
name = "vek"
source = "crates"
categories = ["math"]

[[items]]
name = "vk-mem"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "vk-sync"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "vorbis"
source = "crates"
categories = ["audio"]

[[items]]
name = "voronator"
source = "crates"
categories = ["tools", "mesh"]

[[items]]
name = "vulkano"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "wavefront_obj"
source = "crates"
categories = ["3dformatloaders"]

[[items]]
name = "weasel"
source = "crates"
categories = ["tools"]

[[items]]
name = "wgpu"
source = "crates"
categories = ["3drendering"]

[[items]]
name = "winit"
source = "crates"
categories = ["windowing"]

[[items]]
name = "wlambda"
source = "crates"
categories = ["scripting"]

[[items]]
name = "wrapped2d"
source = "crates"
categories = ["physics"]

[[items]]
name = "wrapping_coords2d"
source = "crates"
categories = ["tools"]
