[[crates]]
name = "aspen"
source = "crates"

[[crates]]
name = "graco"
source = "crates"
homepage = "https://gitlab.com/chrisrabotin/graco/"

[[crates]]
name = "navmesh"
source = "crates"
homepage = "https://github.com/PsichiX/navmesh"

[[crates]]
name = "pathfinding"
source = "crates"

[[crates]]
name = "piston-ai_behavior"
source = "crates"

[[crates]]
name = "steering"
source = "crates"
