[[crates]]
name = "gfx-hal"
source = "crates"

[[crates]]
name = "gfx"
source = "crates"
gitter_url = "https://gitter.im/gfx-rs/gfx"

[[crates]]
name = "luminance"
source = "crates"
gitter_url = "https://gitter.im/phaazon/luminance-rs"

[[crates]]
name = "vulkano"
source = "crates"

[[crates]]
name = "ash"
source = "crates"
gitter_url = "https://gitter.im/MaikKlein/ash"

[[crates]]
name = "glium"
source = "crates"
gitter_url = "https://gitter.im/tomaka/glium"

[[crates]]
name = "glutin"
source = "crates"
gitter_url = "https://gitter.im/tomaka/glutin"

[[crates]]
name = "glfw"
source = "crates"

[[crates]]
name = "kiss3d"
source = "crates"

[[crates]]
name = "three"
source = "crates"

[[crates]]
name = "vk-sync"
source = "crates"

[[crates]]
name = "hephaestus"
source = "crates"

[[crates]]
name = "rendy"
source = "crates"

[[crates]]
name = "gl"
source = "crates"

[[crates]]
name="vk-mem"
source = "crates"

[[crates]]
name="wgpu"
source = "crates"

[[crates]]
name="euc"
source = "crates"

[[crates]]
name = "grr"
source = "crates"
