[[crates]]
name = "conrod"
source = "crates"

[[crates]]
name = "imgui"
source = "crates"

[[crates]]
name = "fungui"
source = "crates"

[[crates]]
name = "nuklear-rust"
source = "crates"

[[crates]]
name = "immi"
source = "crates"

[[crates]]
name = "imgui-ext"
source = "crates"

[[crates]]
name = "rsaarelm/vitral"
source = "github"