[[crates]]
name = "nphysics"
source = "crates"

[[crates]]
name = "wrapped2d"
source = "crates"

[[crates]]
name = "chipmunk"
source = "crates"

[[crates]]
name = "liquidfun"
source = "crates"

[[crates]]
name = "ncollide"
source = "crates"

[[crates]]
name = "collider"
source = "crates"

[[crates]]
name = "mgf"
source = "crates"

[[crates]]
name = "rhusics"
source = "crates"

[[crates]]
name = "nphysics2d"
source = "crates"

[[crates]]
name = "nphysics3d"
source = "crates"
