[[crates]]
name = "glfw"
source = "crates"

[[crates]]
name = "sdl2"
source = "crates"

[[crates]]
name = "glutin"
source = "crates"

[[crates]]
name = "piston_window"
source = "crates"

[[crates]]
name = "winit"
source = "crates"
