[[contributors]]
name = "doppioslash"
links = { twitter = "doppioslash", github = "doppioslash", home = "http://doppioslash.com" }
about = "Graphics Programmer"
description = "Writes on <a href=\"//www.shadercat.com\">shadercat.com</a> about Physically Based Shading and Rendering with Rust and Unity."

[[contributors]]
name = "nxnfufunezn"
links = { twitter = "nxnfufunezn", github = "nxnfufunezn" }
about = "Backend developer and FP enthusiast"

[[contributors]]
name = "bwasty"
links = { github = "bwasty" }
about = "Software Engineer"

[[contributors]]
name = "doomy"
links = { twitter = "piedoomy", github = "piedoomy", home = "https://u9h.design" }
about = "Designer & Rustacean"
description = "Working with the <a href=\"//amethyst.rs\">Amethyst Engine</a> team."

[[contributors]]
name = "ozkriff"
links = { twitter = "ozkriff", github = "ozkriff", home = "https://ozkriff.games" }
about = "System programmer, hobby game developer"
description = "Writes turn-based games in Rust (<a href=https://github.com/ozkriff/zemeroth>Zemeroth</a> atm), runs the <a href=https://twitter.com/rust_gamedev>@rust_gamedev</a> twitter account."
