[[crates]]
name = "fbx_direct"
source = "crates"

[[crates]]
name = "gltf"
source = "crates"

[[crates]]
name = "obj"
source = "crates"

[[crates]]
name = "obj-rs"
source = "crates"

[[crates]]
name = "wavefront_obj"
source = "crates"

[[crates]]
name = "tobj"
source = "crates"

[[crates]]
name = "collada"
source = "crates"

[[crates]]
name = "fbxcel-dom"
source = "crates"

[[crates]]
name = "blend"
source = "crates"