[[crates]]
name = "dyon"
source = "crates"

[[crates]]
name = "gluon"
source = "crates"
gitter_url = "https://gitter.im/gluon-lang/gluon"

[[crates]]
name = "rhai"
source = "crates"

[[crates]]
name = "ketos"
source = "crates"

[[crates]]
name = "hlua"
source = "crates"

[[crates]]
name = "rlua"
source = "crates"

[[crates]]
name = "luajit"
source = "crates"

[[crates]]
name = "lichen"
source = "crates"
