[[crates]]
name = "aseprite"
source = "crates"

[[crates]]
name = "ezing"
source = "crates"

[[crates]]
name = "huxingyi/dust3d"
source = "github"
gitter_url = "https://dust3d.discourse.group/"
homepage = "https://dust3d.org/"

[[crates]]
name = "keyframe"
source = "crates"

[[crates]]
name = "modio"
source = "crates"
gitter_url = "https://discord.mod.io/"

[[crates]]
name = "noise"
source = "crates"

[[crates]]
name = "pyxel"
source = "crates"

[[crates]]
name = "rusttype"
source = "crates"

[[crates]]
name = "sharecart1000"
source = "crates"

[[crates]]
name = "tcod"
source = "crates"

[[crates]]
name = "tiled"
source = "crates"

[[crates]]
name = "tuzz/game-loop"
source = "github"

[[crates]]
name = "weasel"
source = "crates"

