[[crates]]
name = "rust-openvr/rust-openvr"
source = "github"
gitter_url = "https://gitter.im/rust-openvr/rust-openvr"

[[crates]]
name = "rust-webvr"
source = "crates"

[[crates]]
name = "openvr"
source = "crates"

[[crates]]
name = "rovr"
source = "crates"

[[crates]]
name = "libovr"
source = "crates"
